### ISSUE TITLE
Date.php doesn't handle DST

### ISSUE THREAD

**Issue by cdgz** [stdevteam/yii-date#2]
Hi!

The module is quite cool, but it doesn't handle DST :(

In our case, every spring and autumn, some people from my team manually updated offset in settings (not being aware that yii-date module has been developed in Armenia where DST not used at all ^^)

So a small issue, a patch will follow in couple of minutes!
Cheers,
Chingis

**Comment by stdevteam** [comment]
Hi Chingis,

Thanks for the comment. Actually, PHP handles DST internally, so you do not have to deal with this yourself. Maybe you have set wrong timezone?

Thanks
